<!DOCTYPE html>
<html lang="es" dir="ltr">
<head>
  <meta charset="utf-8">
  <?php Mostrar::cabecera(); ?>
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <meta content="IE=edge" http-equiv="X-UA-Compatible">
  <!--[if IE]><link rel="shortcut icon" href="/favicon.ico"><![endif]-->
  <link href="/favicon-16x16.png" rel="icon">
  <meta content="gato v1" name="generator">
  <meta http-equiv="Pragma" content="no-cache">
</head>
<body>
  <?php Mostrar::cuerpo(); ?>
</body>
</html>